apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service   # label matching your Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP  # default and recommended for internal load balancing
