name: Build, Test, and Deploy User Service

on:
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**/package.json'
      - 'Dockerfile'
      - 'k8s/*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linter and unit tests
        run: echo "Skipping tests for demo"  # Insert 'npm run lint && npm test' when you add tests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/user-microservice:latest

      - name: Update deployment YAML with new image
        run: |
          sed -i "s|image: ghcr.io.*/user-microservice:.*|image: ghcr.io/${{ github.repository }}/user-microservice:latest|g" k8s/user-deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/user-deployment.yaml
          git commit -m "ci: update deployment image tag [skip ci]" || echo "No change"
          git push || echo "No changes to commit"

      - name: Trigger Argo CD Sync (optional)
        if: always()
        run: echo "Argo CD will detect manifest change and sync automatically."
